spring:
  application:
    name: backend-school-plus

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./demo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true